Vet Clinic. Milestone: Query And Update Animals Table
CaptainBawa/Vet-Clinic pull request #3
Opened 2023-06-13 21:44 UTC by CaptainBawa

### On this branch:

 - [ ] I inserted new data.
 - [ ] Inside a transaction:
      - Update the animals table by setting the species column to digimon for all animals that have a name ending in mon.
      - Update the animals table by setting the species column to pokemon for all animals that don't have species already set.
      - Verify that changes were made.
      - Commit the transaction.
      - Verify that changes persist after commit.
 
### Screenshot.

![update-species](https://github.com/CaptainBawa/Vet-Clinic/assets/82339317/3d021c88-d4b5-4dfe-a98f-6e09a2225d66)

- [ ] Now, take a deep breath and... Inside a transaction delete all records in the animals table, then roll back the transaction.
     - After the rollback verify if all records in the animals table still exists. After that, you can start breathing as usual ;)
   
### Screenshot.

![delete-rollback](https://github.com/CaptainBawa/Vet-Clinic/assets/82339317/0ef42992-fecb-4978-bb38-e517b218ee9d)

- [ ] Inside a transaction:
     - Delete all animals born after Jan 1st, 2022.
     - Create a savepoint for the transaction.
     - Update all animals' weight to be their weight multiplied by -1.
     - Rollback to the savepoint
     - Update all animals' weights that are negative to be their weight multiplied by -1.
     - Commit transaction

### Screenshot.

![savepoint](https://github.com/CaptainBawa/Vet-Clinic/assets/82339317/0ce8225c-f4d4-4692-ac26-a3b414a5f34a)

- [ ] Write queries to answer the following questions:
     - How many animals are there?
     - How many animals have never tried to escape?
     - What is the average weight of animals?
     - Who escapes the most, neutered or not neutered animals?
     - What is the minimum and maximum weight of each type of animal?
     - What is the average number of escape attempts per animal type of those born between 1990 and 2000?
      
### Screenshot.

![math](https://github.com/CaptainBawa/Vet-Clinic/assets/82339317/c5683cbf-6738-42ac-8009-9c8d667020bd)

2023-06-13 23:04 UTC, laiifuu requested changes
# Status: CHANGES REQUIRED :recycle: 

## Hi @CaptainBawa :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![so-close](https://github.com/CaptainBawa/Vet-Clinic/assets/93520178/e0a771ff-a3fd-42ea-8aca-cc9b843d91da)



## Highlights
- [x] Organized files :heavy_check_mark: 

## Required Changes ♻️: 

- [ ] If you look back on the [project requirements](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_query_update_tables.md#:~:text=Inside%20a%20transaction%20update%20the%20animals%20table%20by%20setting%20the%20species%20column%20to%20unspecified.%20Verify%20that%20change%20was%20made.%20Then%20roll%20back%20the%20change%20and%20verify%20that%20the%20species%20columns%20went%20back%20to%20the%20state%20before%20the%20transaction.), however you the one which states the following: 
![Screenshot from 2023-06-13 23-45-00](https://github.com/CaptainBawa/Vet-Clinic/assets/93520178/83391685-2872-4567-aa5a-a662142dae9f)
Kindly add the transaction for it. 

_Check the comments under the review :point_down:_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-13 23:04 UTC, laiifuu commented on queries.sql
> +UPDATE animals SET species = 'pokemon' WHERE species IS NULL;
Nice job with these updates :clap: However, as stated in the [project requirements](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_query_update_tables.md#:~:text=Inside%20a%20transaction%3A,changes%20persist%20after%20commit.), these updates should be done inside a transaction, and you should verify the changes before and after the commit by making a select query on the table.

2023-06-13 23:04 UTC, laiifuu commented on queries.sql
> +SELECT MAX(weight_kg) FROM animals;
For this question, you should use one query to find the answer, not two. It's possible to utilize `GROUP BY` for this.

2023-06-13 23:04 UTC, laiifuu commented on queries.sql
> +SELECT AVG(escape_attempts) FROM animals WHERE date_of_birth >= '1990-01-01' AND date_of_birth <= '2000-12-31';
Good work on this question :+1: However, if you read the question carefully, you'll see that it states you should find the average number `per animal type`, meaning the average number of escape attempts for the pokemons, and the average number of escape attempts for the digimons. Again, you can utilize `GROUP BY` for this.

2023-06-13 23:04 UTC, laiifuu commented on schema.sql
> +    weight_kg NUMERIC,
When executing this, it gave me an error: 
![Screenshot from 2023-06-14 00-00-02](https://github.com/CaptainBawa/Vet-Clinic/assets/93520178/2bbafd9e-abe9-4fc6-b2fd-53a0fb816507)
I suggest you remove the `,` on line 9.

2023-06-14 08:57 UTC, CaptainBawa commented
### Changes have been made:

- [ ] For this question, you should use one query to find the answer, not two. It's possible to utilize GROUP BY for this.

### Screenshot.

![min-max](https://github.com/CaptainBawa/Vet-Clinic/assets/82339317/fea02e07-1e3a-484d-9267-da0a9980f643)

- [ ] Good work on this question 👍 However, if you read the question carefully, you'll see that it states you should find the average number per animal type, meaning the average number of escape attempts for the pokemons, and the average number of escape attempts for the digimons. Again, you can utilize GROUP BY for this.


### Screenshot. 

![avg](https://github.com/CaptainBawa/Vet-Clinic/assets/82339317/78953bb3-be92-4ac1-b911-dfbbf8bd7a80)


- [ ] Nice job with these updates 👏 However, as stated in the [project requirements](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_query_update_tables.md#:~:text=Inside%20a%20transaction%3A,changes%20persist%20after%20commit.), these updates should be done inside a transaction, and you should verify the changes before and after the commit by making a select query on the table.

- This query is already in a transaction. You can verify it from the previous screenshot. I have now updated it in the queries.sql

2023-06-14 09:06 UTC, gemmen29 approved these changes
Hi @CaptainBawa, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 09:19 UTC, merged